### ISSUE TITLE
When I try and put this into Minecraft it doesn't detect the datapack. I have tried other datapacks and they work perfectly fine. Do you think it's an issue with my minecraft or your datapack?

### ISSUE THREAD

**Issue by Zipezee** [randomuser922/player-health-editor-minecraft#3]

**Comment by Zipezee** [comment]
Also do you have the original I could download? I would really appreciate it!

**Comment by RealSweetPanda** [comment]
you put a zip file or folder in the datapack folder
also, check that int the folder/zip file there is no other folder before you see the data folder if there is move it to the datapack folder so when you enter the folder you see the data folder
@Zipezee

**Comment by CosmicStudio** [comment]
The data pack comes in multiple folders because of how github handles downloading, so you have to make sure you have the right folder in your world data packs folder.  Make sure you put the folder that is in the same directory as the readme file, in your data pack folder.  (The folder you want is called health_editor)

**Comment by randomuser922** [comment]
The data pack comes in multiple folders because of how github handles downloading, so you have to make sure you have the right folder in your world data packs folder.  Make sure you put the folder that is in the same directory as the readme file, in your data pack folder.  (The folder you want is called health_editor)
